# Notification daemon
exec-once = swaync

# Auth agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# Auto mounts USBs and stuff 
exec-once = udiskie &

# lockout screen
# exec-once = swayidle -d -w timeout 2400 'hyprctl dispatcher dpms off && swaylock -f -c 5ca3889ff'

exec-once = todoist-cli sync

# Dropbox<D-->
exec-once = dropbox;

# Starts zsh/waybar after loading secrets
exec = ~/.config/startups/test.sh

# Stretchly (Breaks)
exec-once = sleep 10 && stretchly

# Discord
exec-once = sleep 10 && discord --start-minimized

# exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css

# Wallpapers
exec-once = swww query || swww init


# Workspace Specific
exec-once = [workspace 1 silent] sleep 8 && kitty --hold todoist-cli --color --header --indent list --filter '(today | overdue)'
exec-once = [workspace 9 silent] thunderbird
exec-once = [workspace 9 silent] cryptomator


