# Notification daemon
exec-once = swaync

# Auth agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

# Auto mounts USBs and stuff 
exec-once = udiskie &

# lockout screen
# exec-once = swayidle -d -w timeout 2400 'hyprctl dispatcher dpms off && swaylock -f -c 5ca3889ff'

# Dropbox<D-->
exec-once = dropbox;

exec = ~/.config/startups/test.sh

exec-once = sleep 10 && stretchly
exec-once = sleep 10 && discord --start-minimized

# exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css

# Wallpaper
exec-once = swww query || swww init

