exec-once=dunst
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=import-gsettings
exec-once=hyprstart

# eww scripts
$eww_dir=~/.config/eww/bin
exec-once=$eww_dir/create_temp_files
exec-once=$eww_dir/music_info get_json
exec-once=$eww_dir/workspaces



# Notification daemon
#exec-once = swaync

# Auto mounts USBs and stuff 
exec-once = udiskie &

exec-once = todoist-cli sync

# Dropbox<D-->
exec-once = dropbox;

# Stretchly (Breaks)
exec-once = stretchly

# Discord
exec-once = discord --start-minimized

# Wallpapers
exec-once = swww query || swww init


# Workspace Specific
#exec-once = [workspace 1 silent] sleep 8 && kitty --hold todoist-cli --color --header --indent list --filter '(today | overdue)'
exec-once = [workspace 9 silent] thunderbird
exec-once = [workspace 9 silent] cryptomator


