source = ~/.config/LinkedConfigs/Hypr/autostartHypr.conf
source = ~/.config/LinkedConfigs/Hypr/wallpapersHypr.conf
source = ~/.config/LinkedConfigs/Hypr/bindsHypr.conf

########################################################################## Laptop Specific ############################################################

monitor=,preferred,auto,auto


exec-once = [workspace 1 silent] sleep 8 && kitty --hold todoist-cli --color --header --indent list --filter '(today | overdue)'
exec-once = [workspace 2 silent] sleep 8 && kitty
exec-once = [workspace 3 silent] firefox
exec-once = [workspace 9 silent] thunderbird
exec-once = [workspace 10 silent] cryptomator

$w1 = $we1 $wp1
$w2 = $we2 $wp2
$w3 = $we3 $wp3
$w4 = $we4 $wp4
$w5 = $we5 $wp5
$w6 = $we6 $wp6
$w7 = $we7 $wp7
$w8 = $we8 $wp8
$w9 = $we9 $wp9


windowrule = opacity 0.9 0.9,^(firefox)$
windowrule = opacity 0.9 0.9,^(discord)$
windowrule = opacity 0.9 0.9,^(code)$

#####################################################################################################################################


source = ~/.config/LinkedConfigs/Hypr/extrabindsHypr.conf
source = ~/.config/LinkedConfigs/Hypr/generalHypr.conf
